# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: template
  description: Template for Terraform Components
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




