---
name: Branch
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

permissions: {}

jobs:
  component:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-terraform-component.yml@main
    secrets: inherit
